FROM docker.io/python:3.8.12-slim-buster

RUN apt update && \
    apt install -y --no-install-recommends \
    curl \
    git \
    tini && \
    apt clean &&\
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

RUN python3 -m pip install --no-cache-dir --progress-bar off -U pip setuptools wheel && \
    python3 -m pip install --progress-bar off .[testing]

EXPOSE 8080

ENTRYPOINT ["tini", "--"]
CMD ["sleep", "infinity"]
