version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: cwl-inputs-parser-dev
    container_name: cwl-inputs-parser-dev
    volumes:
      - ${PWD}:/app
    ports:
      - 0.0.0.0:8080:8080
    environment:
      - DEBUG=true
    restart: on-failure
    working_dir: /app
