version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-python
    image: neko-punch-python-dev
    container_name: neko-punch-python-dev
    volumes:
      - ${PWD}:/app
    working_dir: /app
