name: mypy

on: [push, pull_request, workflow_dispatch]

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --no-cache-dir --progress-bar off -U pip setuptools wheel
          python3 -m pip install --no-cache-dir --progress-bar off -U .[testing]
      - name: Check with mypy
        run: |
          mypy --strict --implicit-reexport ./cwl_inputs_parser
